[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "specreboot"
version = "0.1.0"

[project.scripts]
specreboot = "specreboot.cli:cli"

[tool.setuptools.packages.find]
where = ["."]
include = ["specreboot*"]